CREATE TABLE `lifl`.`operations` (
  `row` BIGINT NOT NULL AUTO_INCREMENT,
  `operation_id` BIGINT NOT NULL,
  `time` TIMESTAMP NOT NULL,
  `host` VARCHAR(256),
  `tag` VARCHAR(64),
  `operation` VARCHAR(32) NOT NULL,
  `uid` INT,
  `gid` INT,
  `username` VARCHAR(256),
  `groupname` VARCHAR(256),
  `tty` VARCHAR(16),
  `login_time` TIMESTAMP,
  `remote_host` VARCHAR(256),
  `cmd` VARCHAR(1024),
  `args` VARCHAR(1024),
  `pid` INT,
  `ppid` INT,
  `p_cmd` VARCHAR(1024),
  `file` VARCHAR(1024) NOT NULL,
  `protection` INT,
  `owner` VARCHAR(256),
  `group` VARCHAR(256),
  PRIMARY KEY (`row`)
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE utf8_general_ci;
